#!/usr/bin/env bash
set -euo pipefail

PROJECT_STORAGE_ROOT="${PROJECT_STORAGE_ROOT:-$HOME/gsm8k-grpo}"
export PROJECT_STORAGE_ROOT

export TORCH_HOME="${TORCH_HOME:-$PROJECT_STORAGE_ROOT/.cache/torch}"
export HF_HOME="${HF_HOME:-$PROJECT_STORAGE_ROOT/.cache/huggingface}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$HF_HOME/datasets}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}"
export VLLM_CACHE_ROOT="${VLLM_CACHE_ROOT:-$PROJECT_STORAGE_ROOT/.cache/vllm}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$PROJECT_STORAGE_ROOT/.cache/triton}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$PROJECT_STORAGE_ROOT/.cache}"
export TMPDIR="${TMPDIR:-$PROJECT_STORAGE_ROOT/tmp}"
export TMP="${TMP:-$TMPDIR}"
export TEMP="${TEMP:-$TMPDIR}"

mkdir -p \
  "$PROJECT_STORAGE_ROOT/data/grpo" \
  "$PROJECT_STORAGE_ROOT/models/grpo" \
  "$PROJECT_STORAGE_ROOT/models/eval" \
  "$PROJECT_STORAGE_ROOT/venvs" \
  "$TORCH_HOME" \
  "$HF_HOME" \
  "$HF_DATASETS_CACHE" \
  "$HUGGINGFACE_HUB_CACHE" \
  "$VLLM_CACHE_ROOT" \
  "$TRITON_CACHE_DIR" \
  "$TMPDIR"

printf 'PROJECT_STORAGE_ROOT=%s\n' "$PROJECT_STORAGE_ROOT"
printf 'TORCH_HOME=%s\n' "$TORCH_HOME"
printf 'HF_HOME=%s\n' "$HF_HOME"
printf 'HF_DATASETS_CACHE=%s\n' "$HF_DATASETS_CACHE"
printf 'HUGGINGFACE_HUB_CACHE=%s\n' "$HUGGINGFACE_HUB_CACHE"
printf 'VLLM_CACHE_ROOT=%s\n' "$VLLM_CACHE_ROOT"
printf 'TRITON_CACHE_DIR=%s\n' "$TRITON_CACHE_DIR"
printf 'XDG_CACHE_HOME=%s\n' "$XDG_CACHE_HOME"
printf 'TMPDIR=%s\n' "$TMPDIR"
